export const COMPANY = {
  title: "The Humanoid Robotics Race",
  asOf: "July 2026",
};

export type Robotics = {
  name: string;
  slug: string;
  founded: number;
  hq: string;
  totalFunding: number; // $M, 0 if internal/undisclosed
  valuation: number; // $M, 0 if N/A
  latestRound: string;
  robot: string;
  market: "Home" | "Industrial" | "Logistics" | "Healthcare" | "Broad / Research";
  color: string;
  differentiator: string;
  height?: string;
  weight?: string;
  payload?: string;
  battery?: string;
  dof?: string;
  status: "Independent" | "Subsidiary" | "Public / Pre-IPO";
  confidence: "high" | "medium" | "uncertain";
};

export const COMPANIES: Robotics[] = [
  {
    name: "Figure AI",
    slug: "figure",
    founded: 2022,
    hq: "San Jose, CA",
    totalFunding: 1900,
    valuation: 39000,
    latestRound: "Series C · $1B+ · Sep 2025",
    robot: "Figure 03",
    market: "Industrial",
    color: "#0ea5e9",
    differentiator: "Best-capitalized pure-play humanoid firm. In-house BotQ manufacturing line. Backed by NVIDIA, Brookfield, Intel.",
    height: "1.68m",
    weight: "60kg",
    payload: "20kg",
    battery: "~5hr (wireless charge)",
    dof: "44 (16/hand)",
    status: "Independent",
    confidence: "high",
  },
  {
    name: "Apptronik",
    slug: "apptronik",
    founded: 2016,
    hq: "Austin, TX",
    totalFunding: 1000,
    valuation: 5250,
    latestRound: "Series A-X ext. · $520M · Feb 2026",
    robot: "Apollo",
    market: "Industrial",
    color: "#f97316",
    differentiator: "UT Austin spinout with deep OEM deals — Mercedes-Benz, GXO, John Deere, Google as customer & investor.",
    height: "173cm",
    weight: "72.5kg",
    payload: "25kg",
    battery: "4hr, swappable",
    dof: "modular electric linear actuators",
    status: "Independent",
    confidence: "high",
  },
  {
    name: "Agility Robotics",
    slug: "agility",
    founded: 2015,
    hq: "Salem, OR",
    totalFunding: 641,
    valuation: 2500,
    latestRound: "SPAC merger (Churchill Capital XI) · ~$620M gross · 2026",
    robot: "Digit",
    market: "Logistics",
    color: "#10b981",
    differentiator: "First humanoid company to go public. Real deployments at GXO, Amazon, Toyota, Mercado Libre — 65,000+ operating hours.",
    height: "175cm",
    weight: "65kg",
    payload: "16kg",
    battery: "4–8hr (task-dependent)",
    dof: "—",
    status: "Public / Pre-IPO",
    confidence: "medium",
  },
  {
    name: "1X Technologies",
    slug: "1x",
    founded: 2014,
    hq: "Palo Alto, CA",
    totalFunding: 125,
    valuation: 820,
    latestRound: "Series B · $100M · Jan 2026",
    robot: "NEO",
    market: "Home",
    color: "#eab308",
    differentiator: "Consumer-first home humanoid, OpenAI-backed. Pivoting a fleet to industrial via a 10,000-unit EQT deal, 2026–2030.",
    height: "168cm",
    weight: "30kg",
    payload: "~25kg carry",
    battery: "2–4hr",
    dof: "~75 (22/hand), tendon-driven",
    status: "Independent",
    confidence: "high",
  },
  {
    name: "Unitree",
    slug: "unitree",
    founded: 2016,
    hq: "Hangzhou, China",
    totalFunding: 252,
    valuation: 1700,
    latestRound: "STAR Market IPO filed · targeting ~$608M raise · Mar 2026",
    robot: "G1 / H1 / R1",
    market: "Broad / Research",
    color: "#ef4444",
    differentiator: "Price leader — R1 at $5,900. Largest 2025 shipment volume (32%+ share). First humanoid maker headed for a China IPO.",
    height: "~127cm (G1)",
    weight: "~35kg (G1)",
    payload: "2kg (G1)",
    battery: "~2hr (9000mAh)",
    dof: "23–43, config-dependent",
    status: "Public / Pre-IPO",
    confidence: "medium",
  },
  {
    name: "Fourier Intelligence",
    slug: "fourier",
    founded: 2015,
    hq: "Shanghai, China",
    totalFunding: 110,
    valuation: 1100,
    latestRound: "Series E · ~$110M (800M yuan) · early 2025",
    robot: "GR-3",
    market: "Healthcare",
    color: "#06b6d4",
    differentiator: "Funds its humanoid push with existing rehab-robotics revenue (RehabHub). SoftBank strategic backer.",
    height: "—",
    weight: "—",
    payload: "—",
    battery: "~3hr, dual hot-swap",
    dof: "55",
    status: "Independent",
    confidence: "medium",
  },
  {
    name: "Sunday Robotics",
    slug: "sunday",
    founded: 2024,
    hq: "Mountain View, CA",
    totalFunding: 200,
    valuation: 1150,
    latestRound: "Series B · $165M (Coatue) · Mar 2026",
    robot: "Memo",
    market: "Home",
    color: "#22c55e",
    differentiator: "Founded by ALOHA/diffusion-policy researchers. Fastest unicorn ascent in the group — $1.15B in under 18 months from stealth.",
    height: "—",
    weight: "—",
    payload: "—",
    battery: "—",
    dof: "software-first (10M+ imitation-learning episodes)",
    status: "Independent",
    confidence: "medium",
  },
  {
    name: "Boston Dynamics",
    slug: "boston-dynamics",
    founded: 1992,
    hq: "Waltham, MA",
    totalFunding: 0,
    valuation: 0,
    latestRound: "Hyundai Motor Group subsidiary (acquired 2021)",
    robot: "Atlas (electric)",
    market: "Industrial",
    color: "#64748b",
    differentiator: "Switched Atlas from hydraulic to all-electric. 2026 production run committed exclusively to Hyundai + Google DeepMind.",
    height: "—",
    weight: "—",
    payload: "50kg lift",
    battery: "undisclosed",
    dof: "56, 2.3m reach",
    status: "Subsidiary",
    confidence: "medium",
  },
  {
    name: "Tesla (Optimus)",
    slug: "tesla-optimus",
    founded: 2021,
    hq: "Austin / Fremont, CA",
    totalFunding: 0,
    valuation: 0,
    latestRound: "Internal Tesla Inc. funding",
    robot: "Optimus V3",
    market: "Industrial",
    color: "#dc2626",
    differentiator: "Vertically integrated with FSD/AI5 compute stack. Guidance slipped repeatedly — \"summer 2026\" production start at Fremont.",
    height: "—",
    weight: "—",
    payload: "—",
    battery: "undisclosed",
    dof: "37 joints, 22 DOF/hand",
    status: "Subsidiary",
    confidence: "uncertain",
  },
  {
    name: "Fauna Robotics",
    slug: "fauna",
    founded: 2024,
    hq: "New York, NY",
    totalFunding: 29,
    valuation: 0,
    latestRound: "Acquired by Amazon · Mar 2026 (terms undisclosed)",
    robot: "Sprout",
    market: "Home",
    color: "#ea580c",
    differentiator: "Acquired by Amazon for its kid-sized, approachable design philosophy — a bet on home humanoids feeling less industrial.",
    height: "~107cm (3'6\")",
    weight: "~23kg (50lb)",
    payload: "—",
    battery: "—",
    dof: "—",
    status: "Subsidiary",
    confidence: "medium",
  },
  {
    name: "Weave Robotics",
    slug: "weave",
    founded: 2024,
    hq: "United States (YC-backed)",
    totalFunding: 4,
    valuation: 0,
    latestRound: "Seed · YC S24 + ~$4.2M · 2025",
    robot: "Isaac 0",
    market: "Home",
    color: "#84cc16",
    differentiator: "Pivoted from a general mobile home humanoid to a scoped-down stationary laundry-folder at $7,999 — narrowest go-to-market of the group.",
    height: "stationary unit",
    weight: "—",
    payload: "n/a",
    battery: "n/a (plugged in)",
    dof: "n/a",
    status: "Independent",
    confidence: "uncertain",
  },
];

export const FUNDING_CHART = COMPANIES.filter((c) => c.totalFunding > 0)
  .sort((a, b) => b.totalFunding - a.totalFunding)
  .map((c) => ({ name: c.name, funding: c.totalFunding, color: c.color }));

export const VALUATION_CHART = COMPANIES.filter((c) => c.valuation > 0)
  .sort((a, b) => b.valuation - a.valuation)
  .map((c) => ({ name: c.name, valuation: c.valuation, color: c.color }));

export const MARKET_BREAKDOWN = [
  { market: "Home", count: COMPANIES.filter((c) => c.market === "Home").length, color: "#eab308" },
  { market: "Industrial", count: COMPANIES.filter((c) => c.market === "Industrial").length, color: "#0ea5e9" },
  { market: "Logistics", count: COMPANIES.filter((c) => c.market === "Logistics").length, color: "#10b981" },
  { market: "Healthcare", count: COMPANIES.filter((c) => c.market === "Healthcare").length, color: "#06b6d4" },
  { market: "Broad / Research", count: COMPANIES.filter((c) => c.market === "Broad / Research").length, color: "#ef4444" },
];

export const FOUNDING_TIMELINE = [
  { year: 1992, name: "Boston Dynamics" },
  { year: 2014, name: "1X Technologies" },
  { year: 2015, name: "Fourier Intelligence" },
  { year: 2015, name: "Agility Robotics" },
  { year: 2016, name: "Apptronik" },
  { year: 2016, name: "Unitree" },
  { year: 2021, name: "Tesla Optimus" },
  { year: 2022, name: "Figure AI" },
  { year: 2024, name: "Fauna Robotics" },
  { year: 2024, name: "Sunday Robotics" },
  { year: 2024, name: "Weave Robotics" },
];

export const HERO_STATS = {
  totalFunding: 4260,
  totalValuation: 53170,
  companiesTracked: 11,
  medianFounded: 2016,
};
