export const COMPANY = {
  title: "Robotics Fleet Registry",
  asOf: "July 2026",
};

export type Market =
  | "Home"
  | "Industrial"
  | "Logistics"
  | "Healthcare"
  | "Broad / Research"
  | "Foundation Models";

export type Robotics = {
  name: string;
  slug: string;
  founded: number;
  hq: string;
  totalFunding: number; // $M, 0 if internal/undisclosed
  valuation: number; // $M, 0 if N/A
  latestRound: string;
  robot: string;
  market: Market;
  color: string;
  differentiator: string;
  height?: string;
  weight?: string;
  payload?: string;
  battery?: string;
  dof?: string;
  status: "Independent" | "Subsidiary" | "Public / Pre-IPO";
  confidence: "high" | "medium" | "uncertain";
};

export const COMPANIES: Robotics[] = [
  {
    name: "Figure AI",
    slug: "figure",
    founded: 2022,
    hq: "San Jose, CA",
    totalFunding: 1900,
    valuation: 39000,
    latestRound: "Series C · $1B+ · Sep 2025",
    robot: "Figure 03",
    market: "Industrial",
    color: "#0ea5e9",
    differentiator: "Best-capitalized pure-play humanoid firm. In-house BotQ manufacturing line. Backed by NVIDIA, Brookfield, Intel.",
    height: "1.68m",
    weight: "60kg",
    payload: "20kg",
    battery: "~5hr (wireless charge)",
    dof: "44 (16/hand)",
    status: "Independent",
    confidence: "high",
  },
  {
    name: "Skild AI",
    slug: "skild",
    founded: 2023,
    hq: "Pittsburgh, PA",
    totalFunding: 2000,
    valuation: 14000,
    latestRound: "Series C · $1.4B (SoftBank) · Jan 2026",
    robot: "Skild Brain",
    market: "Foundation Models",
    color: "#2563eb",
    differentiator: "Retrofittable robot-intelligence layer, hardware-agnostic. Tripled its valuation in 7 months out of CMU's robotics labs.",
    height: "n/a (software)",
    weight: "n/a",
    payload: "n/a",
    battery: "n/a",
    dof: "n/a",
    status: "Independent",
    confidence: "high",
  },
  {
    name: "Physical Intelligence",
    slug: "physical-intelligence",
    founded: 2024,
    hq: "San Francisco, CA",
    totalFunding: 1000,
    valuation: 11000,
    latestRound: "In talks · $1B+ · Mar 2026 (Founders Fund, Lightspeed, Bezos)",
    robot: "π0 / π0.5",
    market: "Foundation Models",
    color: "#38bdf8",
    differentiator: "Cross-embodiment robot foundation models with no commercial product yet — a pure research bet, still closing its next round as of this writing.",
    height: "n/a (software)",
    weight: "n/a",
    payload: "n/a",
    battery: "n/a",
    dof: "n/a",
    status: "Independent",
    confidence: "uncertain",
  },
  {
    name: "Apptronik",
    slug: "apptronik",
    founded: 2016,
    hq: "Austin, TX",
    totalFunding: 1000,
    valuation: 5250,
    latestRound: "Series A-X ext. · $520M · Feb 2026",
    robot: "Apollo",
    market: "Industrial",
    color: "#f97316",
    differentiator: "UT Austin spinout with deep OEM deals — Mercedes-Benz, GXO, John Deere, Google as customer & investor.",
    height: "173cm",
    weight: "72.5kg",
    payload: "25kg",
    battery: "4hr, swappable",
    dof: "modular electric linear actuators",
    status: "Independent",
    confidence: "high",
  },
  {
    name: "Neura Robotics",
    slug: "neura",
    founded: 2019,
    hq: "Metzingen, Germany",
    totalFunding: 1600,
    valuation: 7000,
    latestRound: "Series C · $1.4B (Amazon, NVIDIA, Qualcomm, Bosch) · Jun 2026",
    robot: "4NE-1",
    market: "Industrial",
    color: "#c2410c",
    differentiator: "Europe's largest humanoid bet — order book above $1B, targeting 6,000 units shipped in 2026.",
    height: "—",
    weight: "—",
    payload: "—",
    battery: "—",
    dof: "—",
    status: "Independent",
    confidence: "medium",
  },
  {
    name: "Agility Robotics",
    slug: "agility",
    founded: 2015,
    hq: "Salem, OR",
    totalFunding: 641,
    valuation: 2500,
    latestRound: "SPAC merger (Churchill Capital XI) · ~$620M gross · 2026",
    robot: "Digit",
    market: "Logistics",
    color: "#10b981",
    differentiator: "First humanoid company to go public. Real deployments at GXO, Amazon, Toyota, Mercado Libre — 65,000+ operating hours.",
    height: "175cm",
    weight: "65kg",
    payload: "16kg",
    battery: "4–8hr (task-dependent)",
    dof: "—",
    status: "Public / Pre-IPO",
    confidence: "medium",
  },
  {
    name: "Galbot",
    slug: "galbot",
    founded: 2023,
    hq: "Shenzhen, China",
    totalFunding: 1000,
    valuation: 3000,
    latestRound: "~$362M (RMB 2.5B, China's state \"Big Fund\") · Mar 2026",
    robot: "Galbot S1",
    market: "Industrial",
    color: "#b91c1c",
    differentiator: "First embodied-AI investment from China's national chip fund. Deployed on CATL battery lines, pursuing a 2026 Hong Kong IPO.",
    height: "—",
    weight: "—",
    payload: "—",
    battery: "—",
    dof: "dual-arm",
    status: "Independent",
    confidence: "medium",
  },
  {
    name: "1X Technologies",
    slug: "1x",
    founded: 2014,
    hq: "Palo Alto, CA",
    totalFunding: 125,
    valuation: 820,
    latestRound: "Series B · $100M · Jan 2026",
    robot: "NEO",
    market: "Home",
    color: "#eab308",
    differentiator: "Consumer-first home humanoid, OpenAI-backed. Pivoting a fleet to industrial via a 10,000-unit EQT deal, 2026–2030.",
    height: "168cm",
    weight: "30kg",
    payload: "~25kg carry",
    battery: "2–4hr",
    dof: "~75 (22/hand), tendon-driven",
    status: "Independent",
    confidence: "high",
  },
  {
    name: "AgiBot / Zhiyuan",
    slug: "agibot",
    founded: 2023,
    hq: "Shanghai, China",
    totalFunding: 84,
    valuation: 5750,
    latestRound: "Round closed Apr 2026, ahead of ~$1B HK IPO target",
    robot: "Yuanzheng / Lingxi",
    market: "Industrial",
    color: "#facc15",
    differentiator: "Shipped its 10,000th unit by March 2026, making it the world's largest humanoid producer by volume. Founded by ex-Huawei engineers, now targeting a Q3 2026 Hong Kong IPO with CICC, CITIC, and Morgan Stanley as underwriters.",
    height: "—",
    weight: "—",
    payload: "—",
    battery: "—",
    dof: "—",
    status: "Public / Pre-IPO",
    confidence: "uncertain",
  },
  {
    name: "Unitree",
    slug: "unitree",
    founded: 2016,
    hq: "Hangzhou, China",
    totalFunding: 252,
    valuation: 1700,
    latestRound: "STAR Market IPO filed · targeting ~$608M raise · Mar 2026",
    robot: "G1 / H1 / R1",
    market: "Broad / Research",
    color: "#ef4444",
    differentiator: "Price leader — R1 at $5,900. Largest 2025 shipment volume (32%+ share). First humanoid maker headed for a China IPO.",
    height: "~127cm (G1)",
    weight: "~35kg (G1)",
    payload: "2kg (G1)",
    battery: "~2hr (9000mAh)",
    dof: "23–43, config-dependent",
    status: "Public / Pre-IPO",
    confidence: "medium",
  },
  {
    name: "Dexterity Inc",
    slug: "dexterity",
    founded: 2017,
    hq: "Redwood City, CA",
    totalFunding: 296,
    valuation: 1650,
    latestRound: "Series C add-on · $5M · May 2026",
    robot: "DexR / Dex palletizers",
    market: "Logistics",
    color: "#65a30d",
    differentiator: "Container loading and palletizing arms — 1,500+ units deployed with Sumitomo across Japan, plus FedEx and UPS.",
    height: "—",
    weight: "—",
    payload: "—",
    battery: "—",
    dof: "fixed arm",
    status: "Independent",
    confidence: "medium",
  },
  {
    name: "Fourier Intelligence",
    slug: "fourier",
    founded: 2015,
    hq: "Shanghai, China",
    totalFunding: 110,
    valuation: 1100,
    latestRound: "Series E · ~$110M (800M yuan) · early 2025",
    robot: "GR-3",
    market: "Healthcare",
    color: "#06b6d4",
    differentiator: "Funds its humanoid push with existing rehab-robotics revenue (RehabHub). SoftBank strategic backer.",
    height: "—",
    weight: "—",
    payload: "—",
    battery: "~3hr, dual hot-swap",
    dof: "55",
    status: "Independent",
    confidence: "medium",
  },
  {
    name: "Sunday Robotics",
    slug: "sunday",
    founded: 2024,
    hq: "Mountain View, CA",
    totalFunding: 200,
    valuation: 1150,
    latestRound: "Series B · $165M (Coatue) · Mar 2026",
    robot: "Memo",
    market: "Home",
    color: "#22c55e",
    differentiator: "Founded by ALOHA/diffusion-policy researchers. Fastest unicorn ascent in the group — $1.15B in under 18 months from stealth.",
    height: "—",
    weight: "—",
    payload: "—",
    battery: "—",
    dof: "software-first (10M+ imitation-learning episodes)",
    status: "Independent",
    confidence: "medium",
  },
  {
    name: "Standard Bots",
    slug: "standard-bots",
    founded: 2020,
    hq: "Glen Cove, NY",
    totalFunding: 220,
    valuation: 1000,
    latestRound: "Series C · $200M (RoboStrategy) · Jun 2026",
    robot: "RO1 arm",
    market: "Industrial",
    color: "#fb923c",
    differentiator: "No-code industrial arms for machining, welding, and assembly. Committed to 100% US-made parts by 2027; backed by Amazon's Alexa Fund.",
    height: "—",
    weight: "—",
    payload: "—",
    battery: "—",
    dof: "6-axis arm",
    status: "Independent",
    confidence: "medium",
  },
  {
    name: "Field AI",
    slug: "field-ai",
    founded: 2023,
    hq: "Irvine, CA",
    totalFunding: 405,
    valuation: 0,
    latestRound: "Undisclosed lead · 2026",
    robot: "Field Foundation Models",
    market: "Foundation Models",
    color: "#1d4ed8",
    differentiator: "Physics-first \"belief-based\" world models for industrial autonomy with no cloud dependency. Team from DeepMind, JPL, Tesla, NVIDIA; partners with Boston Dynamics.",
    height: "n/a (software)",
    weight: "n/a",
    payload: "n/a",
    battery: "n/a",
    dof: "n/a",
    status: "Independent",
    confidence: "medium",
  },
  {
    name: "Sanctuary AI",
    slug: "sanctuary",
    founded: 2018,
    hq: "Vancouver, Canada",
    totalFunding: 140,
    valuation: 0,
    latestRound: "Series A ext. (Nippon Zeon) · May 2026",
    robot: "Phoenix",
    market: "Industrial",
    color: "#f87171",
    differentiator: "21-DOF hydraulic hands and an explainable hybrid cognitive architecture — but a visible funding gap versus billion-dollar rivals.",
    height: "—",
    weight: "—",
    payload: "—",
    battery: "—",
    dof: "21 (hands)",
    status: "Independent",
    confidence: "medium",
  },
  {
    name: "Collaborative Robotics",
    slug: "cobot",
    founded: 2022,
    hq: "Santa Clara, CA",
    totalFunding: 150,
    valuation: 0,
    latestRound: "Series B · $100M (General Catalyst)",
    robot: "Proxie",
    market: "Logistics",
    color: "#16a34a",
    differentiator: "Omnidirectional swerve-drive mobile cobot built human-safe by design for hospital and warehouse floors.",
    height: "—",
    weight: "—",
    payload: "—",
    battery: "—",
    dof: "mobile base",
    status: "Independent",
    confidence: "medium",
  },
  {
    name: "Vention",
    slug: "vention",
    founded: 2016,
    hq: "Montreal, Canada",
    totalFunding: 250,
    valuation: 0,
    latestRound: "Series D · $110M · Jan 2026",
    robot: "MachineBuilder platform",
    market: "Industrial",
    color: "#0891b2",
    differentiator: "25,000+ robots deployed across 4,000+ facilities, $100M+ ARR — one of the only profitable companies in this space.",
    height: "—",
    weight: "—",
    payload: "—",
    battery: "—",
    dof: "platform/software",
    status: "Independent",
    confidence: "medium",
  },
  {
    name: "Persona AI",
    slug: "persona",
    founded: 2024,
    hq: "Houston, TX",
    totalFunding: 27,
    valuation: 0,
    latestRound: "Pre-seed · $27M (oversubscribed) · 2025",
    robot: "Persona humanoid",
    market: "Industrial",
    color: "#ca8a04",
    differentiator: "Purpose-built humanoid for shipbuilding and steel fab, founded by ex-Figure AI CTO Jerry Pratt. Louisiana state pilot underway.",
    height: "—",
    weight: "—",
    payload: "—",
    battery: "—",
    dof: "—",
    status: "Independent",
    confidence: "medium",
  },
  {
    name: "Chef Robotics",
    slug: "chef",
    founded: 2019,
    hq: "San Francisco, CA",
    totalFunding: 66,
    valuation: 0,
    latestRound: "Series A · $43.1M (Avataar)",
    robot: "Chef arms",
    market: "Industrial",
    color: "#67e8f9",
    differentiator: "Bi-manual food-assembly arms with 100M+ meal servings completed in production — unusually revenue-proven for its funding stage.",
    height: "—",
    weight: "—",
    payload: "—",
    battery: "—",
    dof: "bi-manual arm",
    status: "Independent",
    confidence: "high",
  },
  {
    name: "Boston Dynamics",
    slug: "boston-dynamics",
    founded: 1992,
    hq: "Waltham, MA",
    totalFunding: 0,
    valuation: 0,
    latestRound: "Hyundai bought out SoftBank's remaining ~9.65% stake for $325M, approved ~Jun 2026 — now fully Hyundai-owned",
    robot: "Atlas (electric)",
    market: "Industrial",
    color: "#64748b",
    differentiator: "Now wholly owned by Hyundai after buying out SoftBank's last stake for $325M. Atlas won CNET's \"Best Robot\" at CES 2026 and is slated to deploy at Hyundai's Georgia EV plant, targeting ~25,000 units by 2028.",
    height: "—",
    weight: "—",
    payload: "50kg lift",
    battery: "undisclosed",
    dof: "56, 2.3m reach",
    status: "Subsidiary",
    confidence: "medium",
  },
  {
    name: "Tesla (Optimus)",
    slug: "tesla-optimus",
    founded: 2021,
    hq: "Austin / Fremont, CA",
    totalFunding: 0,
    valuation: 0,
    latestRound: "Internal Tesla Inc. funding",
    robot: "Optimus V3",
    market: "Industrial",
    color: "#dc2626",
    differentiator: "Vertically integrated with FSD/AI5 compute stack. Guidance has firmed up to late July/August 2026 production start at Fremont, following the last Model S/X builds there in early May 2026.",
    height: "—",
    weight: "—",
    payload: "—",
    battery: "undisclosed",
    dof: "37 joints, 22 DOF/hand",
    status: "Subsidiary",
    confidence: "uncertain",
  },
  {
    name: "Covariant",
    slug: "covariant",
    founded: 2017,
    hq: "Berkeley, CA",
    totalFunding: 222,
    valuation: 0,
    latestRound: "Acqui-hired by Amazon · 2026",
    robot: "Covariant Brain",
    market: "Logistics",
    color: "#94a3b8",
    differentiator: "Founders and ~25% of staff acqui-hired by Amazon under a non-exclusive tech license — effectively wound down as an independent company.",
    height: "—",
    weight: "—",
    payload: "—",
    battery: "—",
    dof: "picking AI",
    status: "Subsidiary",
    confidence: "medium",
  },
  {
    name: "Diligent Robotics",
    slug: "diligent",
    founded: 2017,
    hq: "Austin, TX",
    totalFunding: 30,
    valuation: 0,
    latestRound: "Acquired by Serve Robotics · closing Q1 2026",
    robot: "Moxi",
    market: "Healthcare",
    color: "#475569",
    differentiator: "Deployed in 25+ hospitals with 1.25M+ tasks completed. Being folded into Serve Robotics' delivery-robot platform as a consolidation move.",
    height: "—",
    weight: "—",
    payload: "—",
    battery: "—",
    dof: "mobile base",
    status: "Subsidiary",
    confidence: "medium",
  },
  {
    name: "Fauna Robotics",
    slug: "fauna",
    founded: 2024,
    hq: "New York, NY",
    totalFunding: 29,
    valuation: 0,
    latestRound: "Acquired by Amazon · Mar 2026 (terms undisclosed)",
    robot: "Sprout",
    market: "Home",
    color: "#ea580c",
    differentiator: "Acquired by Amazon for its kid-sized, approachable design philosophy — a bet on home humanoids feeling less industrial.",
    height: "~107cm (3'6\")",
    weight: "~23kg (50lb)",
    payload: "—",
    battery: "—",
    dof: "—",
    status: "Subsidiary",
    confidence: "medium",
  },
  {
    name: "Robotera",
    slug: "robotera",
    founded: 2023,
    hq: "Shanghai, China",
    totalFunding: 200,
    valuation: 0,
    latestRound: "Round led by SF Group · $200M+ · May 2026",
    robot: "Robotera humanoid",
    market: "Industrial",
    color: "#4ade80",
    differentiator: "Well-capitalized Chinese humanoid entrant riding the same state- and sovereign-fund wave as Galbot and AgiBot, with fresh SF Group-led capital pushing it toward manufacturing-floor pilots.",
    height: "—",
    weight: "—",
    payload: "—",
    battery: "—",
    dof: "—",
    status: "Independent",
    confidence: "medium",
  },
  {
    name: "TARS Robotics",
    slug: "tars-robotics",
    founded: 2025,
    hq: "China",
    totalFunding: 513,
    valuation: 1900,
    latestRound: "Seed · $513M (Hillhouse, HSG) · 2026",
    robot: "TARS humanoid",
    market: "Industrial",
    color: "#67e8f9",
    differentiator: "A one-year-old startup raising a $513M seed at a $1.9B valuation — an extraordinary, almost unheard-of seed-stage price tag that signals how aggressively Chinese growth capital is chasing humanoid deals sight-unseen.",
    height: "—",
    weight: "—",
    payload: "—",
    battery: "—",
    dof: "—",
    status: "Independent",
    confidence: "uncertain",
  },
  {
    name: "Rhoda AI",
    slug: "rhoda-ai",
    founded: 2024,
    hq: "Palo Alto, CA",
    totalFunding: 450,
    valuation: 0,
    latestRound: "Series A · $450M (Premji Invest) · 2026",
    robot: "Rhoda foundation model",
    market: "Foundation Models",
    color: "#1d4ed8",
    differentiator: "Trains robot foundation models directly from internet video rather than teleoperation data, joining Skild AI and Physical Intelligence in the bet that the brain, not the body, is the moat.",
    height: "n/a (software)",
    weight: "n/a",
    payload: "n/a",
    battery: "n/a",
    dof: "n/a",
    status: "Independent",
    confidence: "medium",
  },
  {
    name: "Weave Robotics",
    slug: "weave",
    founded: 2024,
    hq: "United States (YC-backed)",
    totalFunding: 4,
    valuation: 0,
    latestRound: "Seed · YC S24 + ~$4.2M · 2025",
    robot: "Isaac 0",
    market: "Home",
    color: "#84cc16",
    differentiator: "Pivoted from a general mobile home humanoid to a scoped-down stationary laundry-folder at $7,999 — narrowest go-to-market of the group.",
    height: "stationary unit",
    weight: "—",
    payload: "n/a",
    battery: "n/a (plugged in)",
    dof: "n/a",
    status: "Independent",
    confidence: "uncertain",
  },
];

export const FUNDING_CHART = COMPANIES.filter((c) => c.totalFunding > 0)
  .sort((a, b) => b.totalFunding - a.totalFunding)
  .map((c) => ({ name: c.name, funding: c.totalFunding, color: c.color }));

export const VALUATION_CHART = COMPANIES.filter((c) => c.valuation > 0)
  .sort((a, b) => b.valuation - a.valuation)
  .map((c) => ({ name: c.name, valuation: c.valuation, color: c.color }));

const MARKET_COLORS: Record<Market, string> = {
  Home: "#eab308",
  Industrial: "#0ea5e9",
  Logistics: "#10b981",
  Healthcare: "#06b6d4",
  "Broad / Research": "#ef4444",
  "Foundation Models": "#2563eb",
};

export const MARKETS: Market[] = [
  "Home",
  "Industrial",
  "Logistics",
  "Healthcare",
  "Broad / Research",
  "Foundation Models",
];

export const MARKET_BREAKDOWN = MARKETS.map((market) => ({
  market,
  count: COMPANIES.filter((c) => c.market === market).length,
  color: MARKET_COLORS[market],
}));

export const HERO_STATS = {
  totalFunding: COMPANIES.reduce((s, c) => s + c.totalFunding, 0),
  totalValuation: COMPANIES.reduce((s, c) => s + c.valuation, 0),
  companiesTracked: COMPANIES.length,
  highestValuation: Math.max(...COMPANIES.map((c) => c.valuation)),
  highestValuationCompany: COMPANIES.reduce((a, b) => (b.valuation > a.valuation ? b : a)).name,
};
